export type Country = {
  slug: string;
  name: string;
  flag: string;
};

export const COUNTRIES: Country[] = [
  { slug: "indonesia", name: "Indonesia", flag: "🇮🇩" },
  { slug: "malaysia", name: "Malaysia", flag: "🇲🇾" },
  { slug: "singapore", name: "Singapore", flag: "🇸🇬" },
  { slug: "japan", name: "Japan", flag: "🇯🇵" },
  { slug: "south-korea", name: "South Korea", flag: "🇰🇷" },
  { slug: "china", name: "China", flag: "🇨🇳" },
  { slug: "thailand", name: "Thailand", flag: "🇹🇭" },
  { slug: "vietnam", name: "Vietnam", flag: "🇻🇳" },
  { slug: "philippines", name: "Philippines", flag: "🇵🇭" },
  { slug: "india", name: "India", flag: "🇮🇳" },
  { slug: "united-states", name: "United States", flag: "🇺🇸" },
  { slug: "united-kingdom", name: "United Kingdom", flag: "🇬🇧" },
  { slug: "canada", name: "Canada", flag: "🇨🇦" },
  { slug: "australia", name: "Australia", flag: "🇦🇺" },
  { slug: "germany", name: "Germany", flag: "🇩🇪" },
  { slug: "france", name: "France", flag: "🇫🇷" },
  { slug: "spain", name: "Spain", flag: "🇪🇸" },
  { slug: "italy", name: "Italy", flag: "🇮🇹" },
  { slug: "netherlands", name: "Netherlands", flag: "🇳🇱" },
  { slug: "switzerland", name: "Switzerland", flag: "🇨🇭" },
  { slug: "sweden", name: "Sweden", flag: "🇸🇪" },
  { slug: "norway", name: "Norway", flag: "🇳🇴" },
  { slug: "finland", name: "Finland", flag: "🇫🇮" },
  { slug: "denmark", name: "Denmark", flag: "🇩🇰" },
  { slug: "belgium", name: "Belgium", flag: "🇧🇪" },
  { slug: "austria", name: "Austria", flag: "🇦🇹" },
  { slug: "portugal", name: "Portugal", flag: "🇵🇹" },
  { slug: "ireland", name: "Ireland", flag: "🇮🇪" },
  { slug: "greece", name: "Greece", flag: "🇬🇷" },
  { slug: "poland", name: "Poland", flag: "🇵🇱" },
  { slug: "ukraine", name: "Ukraine", flag: "🇺🇦" },
  { slug: "brazil", name: "Brazil", flag: "🇧🇷" },
  { slug: "mexico", name: "Mexico", flag: "🇲🇽" },
  { slug: "argentina", name: "Argentina", flag: "🇦🇷" },
  { slug: "colombia", name: "Colombia", flag: "🇨🇴" },
  { slug: "chile", name: "Chile", flag: "🇨🇱" },
  { slug: "peru", name: "Peru", flag: "🇵🇪" },
  { slug: "russia", name: "Russia", flag: "🇷🇺" },
  { slug: "turkey", name: "Turkey", flag: "🇹🇷" },
  { slug: "saudi-arabia", name: "Saudi Arabia", flag: "🇸🇦" },
  { slug: "united-arab-emirates", name: "UAE", flag: "🇦🇪" },
  { slug: "egypt", name: "Egypt", flag: "🇪🇬" },
  { slug: "morocco", name: "Morocco", flag: "🇲🇦" },
  { slug: "south-africa", name: "South Africa", flag: "🇿🇦" },
  { slug: "nigeria", name: "Nigeria", flag: "🇳🇬" },
  { slug: "pakistan", name: "Pakistan", flag: "🇵🇰" },
  { slug: "bangladesh", name: "Bangladesh", flag: "🇧🇩" },
  { slug: "new-zealand", name: "New Zealand", flag: "🇳🇿" },
];
